# docker-compose -f docs/docker-compose-docs-serve.yaml up --build
version: "2.4"
services:
  docs:
    build:
      context: ../
      dockerfile: docs/docs.dockerfile
    environment:
      - THEME_DIR=material
    volumes:
      - ..:/main
    ports:
      - 8080:8080
    command:
      - bash
      - -c
      - |
        pwd
        mkdocs --version
        mkdocs serve --config-file ./docs/mkdocs.yml -a 0.0.0.0:8080
        # tail -f /dev/null