site_name: Element Array Ephys
repo_url: https://github.com/datajoint/element-array-ephys
repo_name: datajoint/element-array-ephys
docs_dir: ./src/

theme:
  name: material
  custom_dir: overrides
  logo: assets/elements-logo-black.png
  favicon: assets/elements-logo.png
  features:
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: datajoint
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Element Array Ephys: getting_started/index.md
  - Getting Started:
      - Installation: getting_started/index.md
      - Set Up: getting_started/setup.md
  - Tutorials: tutorials.md
  - Concepts: concepts.md
  - About: about.md
  - API: api.md

plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": "getting_started/index.md"
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons

extra:
  generator: false # Disable watermark
  social:
    - icon: datajoint/dj-logo-white
      link: https://www.datajoint.com/
    - icon: fontawesome/brands/slack
      link: https://datajoint.slack.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datajoint
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DataJointIO
    - icon: fontawesome/brands/github
      link: https://github.com/datajoint
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/datajoint
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCdeCuFOTCXlVMRzh6Wk-lGg

extra_css:
  - stylesheets/extra.css
