site_name: Element Array Ephys
repo_url: https://github.com/A-Baji/element-array-ephys
repo_name: A-Baji/element-array-ephys
docs_dir: ./src/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: datajoint-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: datajoint-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Getting Started:
      - Installation: getting_started/installation.md
      - Set Up: getting_started/setup.md
  - Tutorials: tutorials.md
  - Concepts: concepts.md
  - API: api.md

plugins:
  - search
  - redirects: # mkdocs-redirects
      redirect_maps:
        "index.md": "getting_started/installation.md"
  - mkdocstrings # mkdocstrings, mkdocstrings-python

markdown_extensions:
  - attr_list

# Disable watermark
extra:
  generator: false

extra_css:
  - stylesheets/extra.css
