site_name: Element Array Ephys
repo_url: https://github.com/A-Baji/element-array-ephys
repo_name: A-Baji/element-array-ephys
docs_dir: ./src/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - toc.integrate
  #  - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: datajoint-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: datajoint-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - ⬅ Home: https://www.datajoint.org/
  - Element Array Ephys: /
  - Getting Started:
      - Installation: getting_started/index.md
      - Set Up: getting_started/setup.md
  - Tutorials: tutorials.md
  - Concepts: concepts.md
  - About: about.md
  - API: api.md

plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": "getting_started/index.md"
  - mkdocstrings

markdown_extensions:
  - attr_list

extra:
  generator: false # Disable watermark
  social:
    - icon: fontawesome/brands/slack
      link: https://datajoint.slack.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datajoint
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DataJointIO
    - icon: fontawesome/brands/github
      link: https://github.com/datajoint
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/datajoint
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCdeCuFOTCXlVMRzh6Wk-lGg

extra_css:
  - stylesheets/extra.css
